swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Monthly account transactions
      description: API for getting transactions
      parameters:
        - in: path
          name: accountId
          description: ID of account
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Successfully get the data
          schema:
            $ref: "#/definitions/AccountResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/{transactionId}/transaction:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Details for one transaction
      description: API for getting details for one transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of one transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Successfully get the data
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /note/{transactionId}/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - Note
      summary: add one note
      description: API for add one note
      parameters:
        - in: path
          name: transactionId
          description: ID of one transaction
          required: true
          type: string
        - in: body
          name: body
          description: Post a note
          required: true
          schema:
            $ref: "#/definitions/Note"
      produces:
        - application/json
      responses:
        "200":
          description: Successfully posted the note
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /category/{transactionId}/transaction:
    put:
      security:
        - Bearer: []
      tags:
        - Category
      summary: modify one category
      description: API for modifying one category
      parameters:
        - in: path
          name: transactionId
          description: ID of one transaction
          required: true
          type: string
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/EditCategory"
      produces:
        - application/json
      responses:
        "200":
          description: Successfully updated the category
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /note/{noteId}:
    delete:
      security:
        - Bearer: []
      tags:
        - Note
      summary: delete one note
      description: API for delete one note
      parameters:
        - in: path
          name: noteId
          description: ID of one note
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Successfully deletted the note
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Note
      summary: Modify one note
      description: API for Modify one note
      parameters:
        - in: path
          name: noteId
          description: ID of one note
          required: true
          type: string
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Note"
      produces:
        - application/json
      responses:
        "200":
          description: Successfully modified
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ProfilResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Note:
    properties:
      note:
        type: string
        description: one note
  NoteResponse:
    properties:
      id:
        type: string
        description: id of the note
      note:
        type: string
        description: one note
  TransactionResponse:
    properties:
      id:
        type: string
        description: id of the transaction
      date:
        type: string
        description: date of the transaction
      description:
        type: string
        description: description of the transaction
      amount:
        type: number
        description: amount
      type:
        type: string
        description: transaction type
      category:
        type: string
        description: category
      notes:
        type: array
        items: 
          $ref: "#/definitions/NoteResponse"
  EditCategory:
    properties:
      category:
        type: string
        description: transaction id
  AccountResponse:
    properties:
      id:
        type: string
        description: user id
      name:
        type: string
        description: account name
      balance:
        type: string
        description: balance
      body:
        type: array
        items:
          $ref: "#/definitions/TransactionResponse"
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  ProfilResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
          usename:
            type: string
          first name:
            type: string
          last name:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
